
package parkservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "parkeerplaatsService", targetNamespace = "http://parkeerplaatsservice/berichten/message", wsdlLocation = "file:/C:/Users/lucas/workspace/parkserviceopenshift/parkeerplaatsservice/src/main/java/xmlfiles/ParkeerplaatsService.wsdl")
public class ParkeerplaatsService
    extends Service
{

    private final static URL PARKEERPLAATSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PARKEERPLAATSSERVICE_EXCEPTION;
    private final static QName PARKEERPLAATSSERVICE_QNAME = new QName("http://parkeerplaatsservice/berichten/message", "parkeerplaatsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/lucas/workspace/parkserviceopenshift/parkeerplaatsservice/src/main/java/xmlfiles/ParkeerplaatsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARKEERPLAATSSERVICE_WSDL_LOCATION = url;
        PARKEERPLAATSSERVICE_EXCEPTION = e;
    }

    public ParkeerplaatsService() {
        super(__getWsdlLocation(), PARKEERPLAATSSERVICE_QNAME);
    }

    public ParkeerplaatsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARKEERPLAATSSERVICE_QNAME, features);
    }

    public ParkeerplaatsService(URL wsdlLocation) {
        super(wsdlLocation, PARKEERPLAATSSERVICE_QNAME);
    }

    public ParkeerplaatsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARKEERPLAATSSERVICE_QNAME, features);
    }

    public ParkeerplaatsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ParkeerplaatsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PkSInterface
     */
    @WebEndpoint(name = "WS-Port")
    public PkSInterface getWSPort() {
        return super.getPort(new QName("http://parkeerplaatsservice/berichten/message", "WS-Port"), PkSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PkSInterface
     */
    @WebEndpoint(name = "WS-Port")
    public PkSInterface getWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://parkeerplaatsservice/berichten/message", "WS-Port"), PkSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARKEERPLAATSSERVICE_EXCEPTION!= null) {
            throw PARKEERPLAATSSERVICE_EXCEPTION;
        }
        return PARKEERPLAATSSERVICE_WSDL_LOCATION;
    }

}
